name: Test Actions

on:
  push:
    branch: 
      - 'main'

jobs:
  my_hello:
    runs-on: ubuntu-latest
    steps:
      - name: just say hello
        run: 
          echo "Bonjour Tout le monde."

      
    
